// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB81I6BQtPGNnMuk-CnA8__rr1P2Thmiag',
    appId: '1:307860351450:web:c413e7e44453fb7444f8e3',
    messagingSenderId: '307860351450',
    projectId: 'maricielocalzado',
    authDomain: 'maricielocalzado.firebaseapp.com',
    storageBucket: 'maricielocalzado.firebasestorage.app',
    measurementId: 'G-4LHYPGBJNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLRSJPCzbgoLvoCSIH_gogiPlW1VF2kY',
    appId: '1:307860351450:android:92462a9e0d473cd544f8e3',
    messagingSenderId: '307860351450',
    projectId: 'maricielocalzado',
    storageBucket: 'maricielocalzado.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPq26zxEOcB7FqeYIcyCP6bGWEvL6m45U',
    appId: '1:307860351450:ios:b4bb1b6cbdb8b18844f8e3',
    messagingSenderId: '307860351450',
    projectId: 'maricielocalzado',
    storageBucket: 'maricielocalzado.firebasestorage.app',
    iosBundleId: 'com.example.calzadosLuciana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPq26zxEOcB7FqeYIcyCP6bGWEvL6m45U',
    appId: '1:307860351450:ios:b4bb1b6cbdb8b18844f8e3',
    messagingSenderId: '307860351450',
    projectId: 'maricielocalzado',
    storageBucket: 'maricielocalzado.firebasestorage.app',
    iosBundleId: 'com.example.calzadosLuciana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB81I6BQtPGNnMuk-CnA8__rr1P2Thmiag',
    appId: '1:307860351450:web:2a1e86c80211e5e344f8e3',
    messagingSenderId: '307860351450',
    projectId: 'maricielocalzado',
    authDomain: 'maricielocalzado.firebaseapp.com',
    storageBucket: 'maricielocalzado.firebasestorage.app',
    measurementId: 'G-96VBBBEKL8',
  );
}
